version: "3.8"
services:
  backend:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./.env
    volumes:
      - "./:/app/"
    networks:
      - trandung
networks:
  trandung: